import type { MetricConfig } from "./generator";

export const platformMetricConfigs: Record<string, MetricConfig[]> = {
  "google-analytics": [
    { key: "sessions", label: "Sessions", baseline: 820, dailyGrowth: 0.0008, noise: 0.15, weekendDip: 0.3, format: "number" },
    { key: "users", label: "Users", baseline: 610, dailyGrowth: 0.0005, noise: 0.12, weekendDip: 0.25, format: "number" },
    { key: "pageViews", label: "Page Views", baseline: 2100, dailyGrowth: 0.001, noise: 0.18, weekendDip: 0.35, format: "number" },
    { key: "bounceRate", label: "Bounce Rate", baseline: 42, dailyGrowth: -0.0003, noise: 0.08, weekendDip: 0, format: "percent", min: 25, max: 65 },
    { key: "avgSessionDuration", label: "Avg. Session Duration", baseline: 185, dailyGrowth: 0.0004, noise: 0.1, weekendDip: 0.1, format: "number" },
    { key: "conversions", label: "Conversions", baseline: 3, dailyGrowth: 0.001, noise: 0.35, weekendDip: 0.4, format: "number", min: 0 },
  ],
  "google-ads": [
    { key: "spend", label: "Spend", baseline: 285, dailyGrowth: 0.0003, noise: 0.1, weekendDip: 0.15, format: "currency" },
    { key: "clicks", label: "Clicks", baseline: 210, dailyGrowth: 0.0006, noise: 0.15, weekendDip: 0.2, format: "number" },
    { key: "impressions", label: "Impressions", baseline: 8200, dailyGrowth: 0.0008, noise: 0.12, weekendDip: 0.15, format: "number" },
    { key: "ctr", label: "CTR", baseline: 2.56, dailyGrowth: 0.0002, noise: 0.08, weekendDip: 0, format: "percent", min: 0.5, max: 8 },
    { key: "conversions", label: "Conversions", baseline: 1.6, dailyGrowth: 0.001, noise: 0.4, weekendDip: 0.3, format: "number", min: 0 },
    { key: "costPerConversion", label: "Cost Per Conversion", baseline: 178, dailyGrowth: -0.0005, noise: 0.15, weekendDip: 0, format: "currency", min: 50 },
  ],
  gmb: [
    { key: "profileViews", label: "Profile Views", baseline: 330, dailyGrowth: 0.0007, noise: 0.12, weekendDip: 0.1, format: "number" },
    { key: "searchViews", label: "Search Views", baseline: 240, dailyGrowth: 0.0006, noise: 0.1, weekendDip: 0.08, format: "number" },
    { key: "mapViews", label: "Map Views", baseline: 88, dailyGrowth: 0.0008, noise: 0.15, weekendDip: 0.05, format: "number" },
    { key: "phoneCalls", label: "Phone Calls", baseline: 2.2, dailyGrowth: 0.0004, noise: 0.4, weekendDip: 0.6, format: "number", min: 0 },
    { key: "directionRequests", label: "Direction Requests", baseline: 4.8, dailyGrowth: 0.0006, noise: 0.25, weekendDip: 0.2, format: "number", min: 0 },
    { key: "websiteClicks", label: "Website Clicks", baseline: 10.5, dailyGrowth: 0.0005, noise: 0.2, weekendDip: 0.15, format: "number", min: 0 },
  ],
  facebook: [
    { key: "followers", label: "Followers", baseline: 1595, dailyGrowth: 0.002, noise: 0.01, weekendDip: 0, format: "number" },
    { key: "pageViews", label: "Page Views", baseline: 85, dailyGrowth: 0.001, noise: 0.25, weekendDip: 0.15, format: "number" },
    { key: "postEngagement", label: "Post Engagement", baseline: 120, dailyGrowth: 0.0015, noise: 0.3, weekendDip: 0.1, format: "number" },
    { key: "reach", label: "Reach", baseline: 2500, dailyGrowth: 0.002, noise: 0.2, weekendDip: 0.1, format: "number" },
    { key: "likes", label: "New Page Likes", baseline: 3.5, dailyGrowth: 0.003, noise: 0.5, weekendDip: 0, format: "number", min: 0 },
    { key: "posts", label: "Posts", baseline: 0.7, dailyGrowth: 0, noise: 0.6, weekendDip: 0.5, format: "number", min: 0 },
  ],
  instagram: [
    { key: "followers", label: "Followers", baseline: 1035, dailyGrowth: 0.0015, noise: 0.01, weekendDip: 0, format: "number" },
    { key: "reach", label: "Reach", baseline: 1800, dailyGrowth: 0.002, noise: 0.25, weekendDip: 0.08, format: "number" },
    { key: "views", label: "Views", baseline: 780, dailyGrowth: 0.002, noise: 0.2, weekendDip: 0.05, format: "number" },
    { key: "likes", label: "Likes", baseline: 10, dailyGrowth: 0.001, noise: 0.35, weekendDip: 0.05, format: "number", min: 0 },
    { key: "saves", label: "Saves", baseline: 1.2, dailyGrowth: 0.001, noise: 0.5, weekendDip: 0, format: "number", min: 0 },
    { key: "comments", label: "Comments", baseline: 0.3, dailyGrowth: 0.001, noise: 0.6, weekendDip: 0, format: "number", min: 0 },
  ],
  youtube: [
    { key: "views", label: "Views", baseline: 950, dailyGrowth: 0.003, noise: 0.2, weekendDip: 0.05, format: "number" },
    { key: "watchTime", label: "Watch Time (hrs)", baseline: 42, dailyGrowth: 0.002, noise: 0.18, weekendDip: 0.05, format: "number" },
    { key: "subscribers", label: "Subscribers", baseline: 92, dailyGrowth: 0.003, noise: 0.01, weekendDip: 0, format: "number" },
    { key: "likes", label: "Likes", baseline: 22, dailyGrowth: 0.002, noise: 0.3, weekendDip: 0, format: "number", min: 0 },
    { key: "comments", label: "Comments", baseline: 1.6, dailyGrowth: 0.001, noise: 0.5, weekendDip: 0, format: "number", min: 0 },
    { key: "videosPublished", label: "Videos Published", baseline: 0.5, dailyGrowth: 0, noise: 0.8, weekendDip: 0.8, format: "number", min: 0 },
  ],
  "meta-ads": [
    { key: "spend", label: "Spend", baseline: 210, dailyGrowth: 0.0004, noise: 0.1, weekendDip: 0.1, format: "currency" },
    { key: "impressions", label: "Impressions", baseline: 6200, dailyGrowth: 0.001, noise: 0.15, weekendDip: 0.08, format: "number" },
    { key: "clicks", label: "Clicks", baseline: 160, dailyGrowth: 0.0008, noise: 0.18, weekendDip: 0.1, format: "number" },
    { key: "ctr", label: "CTR", baseline: 2.89, dailyGrowth: 0.0002, noise: 0.06, weekendDip: 0, format: "percent", min: 0.5, max: 8 },
    { key: "cpc", label: "Avg. CPC", baseline: 0.22, dailyGrowth: 0.0001, noise: 0.15, weekendDip: 0, format: "currency", min: 0.05 },
    { key: "conversions", label: "Messaging Conv.", baseline: 2, dailyGrowth: 0.001, noise: 0.4, weekendDip: 0.3, format: "number", min: 0 },
    { key: "reach", label: "Reach", baseline: 5200, dailyGrowth: 0.0012, noise: 0.15, weekendDip: 0.08, format: "number" },
  ],
  ringcentral: [
    { key: "totalCalls", label: "Total Calls", baseline: 5.2, dailyGrowth: 0.001, noise: 0.3, weekendDip: 0.7, format: "number", min: 0 },
    { key: "answered", label: "Answered", baseline: 4.4, dailyGrowth: 0.001, noise: 0.28, weekendDip: 0.7, format: "number", min: 0 },
    { key: "missed", label: "Missed", baseline: 0.8, dailyGrowth: -0.001, noise: 0.5, weekendDip: 0.7, format: "number", min: 0 },
    { key: "avgDuration", label: "Avg. Duration (min)", baseline: 4.2, dailyGrowth: 0.0003, noise: 0.15, weekendDip: 0, format: "number", min: 1 },
    { key: "uniqueCallers", label: "Unique Callers", baseline: 3.3, dailyGrowth: 0.001, noise: 0.3, weekendDip: 0.65, format: "number", min: 0 },
    { key: "answerRate", label: "Answer Rate", baseline: 84.6, dailyGrowth: 0.0002, noise: 0.05, weekendDip: 0, format: "percent", min: 50, max: 100 },
  ],
  "go-high-level": [
    { key: "emailsSent", label: "Emails Sent", baseline: 140, dailyGrowth: 0.0003, noise: 0.2, weekendDip: 0.5, format: "number", min: 0 },
    { key: "openRate", label: "Open Rate", baseline: 24.8, dailyGrowth: 0.0002, noise: 0.08, weekendDip: 0, format: "percent", min: 10, max: 50 },
    { key: "clickRate", label: "Click Rate", baseline: 3.6, dailyGrowth: 0.0003, noise: 0.12, weekendDip: 0, format: "percent", min: 0.5, max: 15 },
    { key: "bounces", label: "Bounces", baseline: 1.4, dailyGrowth: -0.001, noise: 0.5, weekendDip: 0.5, format: "number", min: 0 },
    { key: "unsubscribes", label: "Unsubscribes", baseline: 0.27, dailyGrowth: -0.001, noise: 0.6, weekendDip: 0, format: "number", min: 0 },
    { key: "newContacts", label: "New Contacts", baseline: 5.2, dailyGrowth: 0.0008, noise: 0.3, weekendDip: 0.3, format: "number", min: 0 },
  ],
  linkedin: [
    { key: "impressions", label: "Impressions", baseline: 1850, dailyGrowth: 0.0015, noise: 0.18, weekendDip: 0.2, format: "number" },
    { key: "clicks", label: "Clicks", baseline: 47, dailyGrowth: 0.001, noise: 0.22, weekendDip: 0.2, format: "number" },
    { key: "ctr", label: "CTR", baseline: 2.55, dailyGrowth: 0.0002, noise: 0.08, weekendDip: 0, format: "percent", min: 0.5, max: 8 },
    { key: "followers", label: "Followers", baseline: 245, dailyGrowth: 0.002, noise: 0.01, weekendDip: 0, format: "number" },
    { key: "adSpend", label: "Ad Spend", baseline: 135, dailyGrowth: 0.0005, noise: 0.1, weekendDip: 0.15, format: "currency" },
    { key: "leads", label: "Leads", baseline: 1.3, dailyGrowth: 0.001, noise: 0.45, weekendDip: 0.4, format: "number", min: 0 },
  ],
};
